sogenactif_sending:
    path:     /
    defaults: { _controller: SogenactifBundle:Transaction:sending }

sogenactif_normal:
    path:     /response
    defaults: { _controller: SogenactifBundle:Transaction:response }
    methods: POST