sogenactif_sending:
    path:     /
    defaults: { _controller: SogenactifBundle:Transaction:sending }

sogenactif_normal:
    path:     /normal
    defaults: { _controller: SogenactifBundle:Transaction:normalResponse }
    methods: POST

sogenactif_autoresponse:
    path:     /autoresponse
    defaults: { _controller: SogenactifBundle:Transaction:autoResponse }