# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    user.form.registration:
        class: UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    user.form.profile:
        class: UserBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: app_user_profile }
        arguments: [%fos_user.model.user.class%]
