baptism_select:
    path:       /selection
    defaults:   { _controller: AppBundle:Baptism:select }

baptism_purchase:
    path:       /acheter
    defaults:   { _controller: AppBundle:Baptism:purchase }