baptism_info_index:
    path:     /index
    defaults: { _controller: "AppBundle:Baptism:index" }
    methods:  GET

baptism_info_show:
    path:     /show
    defaults: { _controller: "AppBundle:Baptism:show" }
    methods:  POST

baptism_info_new:
    path:     /new
    defaults: { _controller: "AppBundle:Baptism:new" }
    methods:  [GET, POST]

baptism_info_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Baptism:edit" }
    methods:  [GET, POST]

baptism_info_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Baptism:delete" }
    methods:  DELETE

baptism_select:
    path:     /select
    defaults: { _controller: "AppBundle:Baptism:select"}
    methods: [GET, POST]

baptism_purchase:
    path:     /purchase
    defaults: { _controller: "AppBundle:Baptism:purchase", id: 0 }
    methods:  [GET, POST]