baptism_page:
    path:       /
    defaults:   { _controller: AppBundle:Baptism:search }

baptism_select:
    path:       /selection
    defaults:   { _controller: AppBundle:Baptism:select }

baptism_purchase:
    path:       /achat/{reference}
    defaults:   { _controller: AppBundle:Baptism:purchase }

baptism_guest:
    path:       /reserver/{id}
    defaults:   { _controller: AppBundle:BaptismHasUser:reserve }
    requirements:
      id: \d+