our_restaurants:
    path:       /
    defaults:   { _controller: AppBundle:Restaurant:list }

restaurant:
    path:       /restaurant/{slug}
    defaults:   { _controller: AppBundle:Restaurant:show }