our_restaurants:
    path:       /nos-restaurants
    defaults:   { _controller: AppBundle:Restaurant:list }

restaurant:
    path:       /restaurant/{slug}
    defaults:   { _controller: AppBundle:Restaurant:show }