UserBundle\Entity\User:
    type:  entity
    table: user
    repositoryClass: UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        civility:
            type: string
            length: '1'
        firstName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
        slug:
            type: string
            length: 255
            unique: true
            nullable: true
        birthDate:
            type: date
        address:
            type: string
            length: 255
        zipCode:
            type: string
            length: 5
        city:
            type: string
            length: 255
        mobilePhone:
            type: string
            length: 40
            unique: true
        level:
            type: integer
            nullable: true
        rating:
            type: float
            nullable: true
        participation:
            type: integer
            nullable: true
    oneToMany:
        baptismsHasUser:
            targetEntity: AppBundle\Entity\BaptismHasUser
            mappedBy: user
        payments:
            targetEntity: AppBundle\Entity\Payment
            mappedBy: user
        medias:
            targetEntity: AppBundle\Entity\Media
            mappedBy: user
        restaurants:
            targetEntity: AppBundle\Entity\Restaurant
            mappedBy: user
    lifecycleCallbacks: {  }