UserBundle\Entity\User:
    type:  entity
    table: user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
        slug:
            type: string
            length: 255
            unique: true
        birthDate:
            type: date
            nullable: true
        biography:
            type: text
            nullable: true
        signatureDish:
            type: string
            length: 255
            nullable: true
        rating:
            type: float
            nullable: true
        phone:
            type: string
            length: 40
            nullable: true
        level:
            type: integer
            nullable: true
        participation:
            type: integer
            nullable: true
        profession:
            type: string
            length: 255
            nullable: true
    oneToMany:
        baptismsHasUser:
            targetEntity: AppBundle\Entity\BaptismHasUser
            mappedBy: user
        payments:
            targetEntity: AppBundle\Entity\Payment
            mappedBy: user
        medias:
            targetEntity: AppBundle\Entity\Media
            mappedBy: user
        restaurants:
            targetEntity: AppBundle\Entity\Restaurant
            mappedBy: user
    lifecycleCallbacks: {  }