UserBundle\Entity\User:
    type:  entity
    table: user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
        slug:
            type: string
            length: 255
            unique: true
        birthDate:
            type: date
            nullable: true
        biography:
            type: text
        signatureDish:
            type: string
            length: 255
        rating:
            type: float
        phone:
            type: string
            length: 40
        level:
            type: integer
        participation:
            type: integer
        profession:
            type: string
            length: 255
    oneToMany:
        baptemsHasUser:
            targetEntity: AppBundle\Entity\BaptemHasUser
            mappedBy: user
    lifecycleCallbacks: {  }