services:
    user.email_confirm_listener:
        class: UserBundle\EventListener\EmailConfirmationListener
        tags:
            - { name: kernel.event_subscriber }

    user.new_user_slug:
        class: UserBundle\Services\UserSlugService