AppBundle\Entity\BaptemHasUser:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\BaptemHasUserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        role:
            type: boolean
    manyToOne:
        baptem:
            targetEntity: AppBundle\Entity\Baptem
            inversedBy: baptemsHasUser
            joinColumn:
                name: baptem_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
