AppBundle\Entity\Baptem:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\BaptemRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        status:
            type: boolean
        date:
            type: date
        places:
            type: integer
    manyToOne:
        service:
            targetEntity: AppBundle\Entity\Service
            inversedBy: baptems
            joinColumn:
                name: service_id
                referencedColumnName: id
    oneToMany:
        payments:
            targetEntity: AppBundle\Entity\Payment
            mappedBy: baptem
        baptemsHasUser:
            targetEntity: AppBundle\Entity\BaptemHasUser
            mappedBy: baptem
    lifecycleCallbacks: {  }
