AppBundle\Entity\BaptismHasUser:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\BaptismHasUserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        role:
            type: boolean
    manyToOne:
        baptism:
            targetEntity: AppBundle\Entity\Baptism
            inversedBy: baptismsHasUser
            joinColumn:
                name: baptism_id
                referencedColumnName: id
        user:
            targetEntity: UserBundle\Entity\User
            inversedBy: baptismsHasUser
            joinColumn:
                name: user_id
                referencedColumnName: id
    oneToOne:
        payment:
            targetEntity: AppBundle\Entity\Payment
            mappedBy: baptism_has_user
    lifecycleCallbacks: {  }
