AppBundle\Entity\Payment:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PaymentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
        productName:
            type: string
            length: 255
        status:
            type: string
            length: 255
        confirmationSent:
            type: boolean
    manyToOne:
        user:
            targetEntity: UserBundle\Entity\User
            inversedBy: payments
            joinColumn:
                name: user_id
                referencedColumnName: id
    oneToOne:
        baptism_has_user:
            targetEntity: AppBundle\Entity\BaptismHasUser
            inversedBy: payment
            joinColumn:
                name: baptism_has_user_id
                referencedColumnName: id
        transaction:
            targetEntity: SogenactifBundle\Entity\Transaction
            inversedBy: payment
            joinColumn:
                name: transaction_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
