AppBundle\Entity\Price:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PriceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        value:
            type: float
    manyToOne:
        product:
            targetEntity: AppBundle\Entity\Product
            inversedBy: prices
            joinColumn:
                name: product_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
