AppBundle\Entity\ServiceOpeningException:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ServiceOpeningExceptionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: date
        status:
            type: integer
    manyToOne:
        service:
            targetEntity: AppBundle\Entity\Service
            inversedBy: serviceOpeningExceptions
            joinColumn:
                name: service_id
                referencedColumnName: id
        restaurant:
            targetEntity: AppBundle\Entity\Restaurant
            inversedBy: serviceOpeningExceptions
            joinColumn:
                name: restaurant_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
