AppBundle\Entity\ServiceOpening:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ServiceOpeningRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        monday:
            type: integer
        tuesday:
            type: integer
        wednesday:
            type: integer
        thursday:
            type: integer
        friday:
            type: integer
        saturday:
            type: integer
        sunday:
            type: integer
    lifecycleCallbacks: {  }
