BlogBundle\Entity\Post:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\PostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
            unique: true
        description:
            type: string
            length: 255
        keywords:
            type: string
            length: 255
        content:
            type: text
        views:
            type: integer
        visibility:
            type: string
            length: 255
        createdAt:
            type: datetime
        lastUpdatedAt:
            type: datetime

    manyToOne:
        category:
            targetEntity: BlogBundle\Entity\Category
            inversedBy: posts
            joinColumn:
                name: category_id
                referencedColumnName: id
    manyToMany:
        tags:
            targetEntity: BlogBundle\Entity\Tag
            inversedBy: blogPosts
            joinTable:
                name: post_has_tag
                joinColumns:
                    post_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id

        medias:
            targetEntity: AppBundle\Entity\Media
            inversedBy: posts
            joinTable:
                name: post_has_media
                joinColumns:
                    post_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    media_id:
                        referencedColumnName: id

    lifecycleCallbacks: {  }
