BlogBundle\Entity\Tag:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\TagRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
            unique: true
        slug:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
